/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.udistrital.modelosmemoria.presentacionPDinamica;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;

/**
 *
 * @author Admin
 */
public class VistaPDinamica extends javax.swing.JFrame {

    private ModeloPDinamica modeloPDinamica;
    private ControladorPDinamica controladorPDinamica;
    private JPanel memoria;
    private MemoriaPDinamica objMemoria;

    /**
     * Creates new form VistaPDinamica
     */
    public VistaPDinamica(ModeloPDinamica modelo) {
        modeloPDinamica = modelo;
        initComponents();
        inicializarMemoria();
        capturarEventos();
    }

    public ControladorPDinamica getControl() {
        if (controladorPDinamica == null) {
            controladorPDinamica = new ControladorPDinamica(this);
        }
        return controladorPDinamica;
    }

    public void inicializarMemoria() {
        getContentPane().setLayout(null);
        memoria = new JPanel();
        getContentPane().add(memoria);
        memoria.setBounds(500, 30, 180, 550);
        memoria.setBorder(new SoftBevelBorder(BevelBorder.LOWERED, null, null, null, null));
        objMemoria = new MemoriaPDinamica();
        memoria.add(objMemoria);
    }

    public void capturarEventos() {
        btnAgregarProceso.addActionListener(getControl());
        btnReinicio.addActionListener(getControl());
        checkBox.addActionListener(getControl());
    }

    public ModeloPDinamica getModeloPDinamica() {
        return modeloPDinamica;
    }

    public MemoriaPDinamica getObjMemoria() {
        return objMemoria;
    }

    public void setObjMemoria(MemoriaPDinamica objMemoria) {
        this.objMemoria = objMemoria;
    }

    public JComboBox<String> getComboProceso() {
        return comboProceso;
    }

    public void setComboProceso(JComboBox<String> comboProceso) {
        this.comboProceso = comboProceso;
    }

    public ButtonGroup getBtnGroup() {
        return btnGroup;
    }

    public void setBtnGroup(ButtonGroup btnGroup) {
        this.btnGroup = btnGroup;
    }

    public JRadioButton getRadio1() {
        return radio1;
    }

    public void setRadio1(JRadioButton radio1) {
        this.radio1 = radio1;
    }

    public JRadioButton getRadio2() {
        return radio2;
    }

    public void setRadio2(JRadioButton radio2) {
        this.radio2 = radio2;
    }

    public JRadioButton getRadio3() {
        return radio3;
    }

    public void setRadio3(JRadioButton radio3) {
        this.radio3 = radio3;
    }

    public JCheckBox getCheckBox() {
        return checkBox;
    }

    public void setCheckBox(JCheckBox checkBox) {
        this.checkBox = checkBox;
    }
    public JButton getBtnAgregarProceso() {
        return btnAgregarProceso;
    }

    public void setBtnAgregarProceso(JButton btnAgregarProceso) {
        this.btnAgregarProceso = btnAgregarProceso;
    }

    public JButton getBtnReinicio() {
        return btnReinicio;
    }

    public void setBtnReinicio(JButton btnReinicio) {
        this.btnReinicio = btnReinicio;
    }

    public JList<String> getjList1() {
        return jList1;
    }

    public void setjList1(JList<String> jList1) {
        this.jList1 = jList1;
    }

    public JList<String> getjList2() {
        return jList2;
    }

    public void setjList2(JList<String> jList2) {
        this.jList2 = jList2;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboProceso = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnAgregarProceso = new javax.swing.JButton();
        btnReinicio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        radio2 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        radio1 = new javax.swing.JRadioButton();
        checkBox = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Procesos");

        comboProceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "64K", "128K", "256K", "512K", "1024K", "2048K", "4096K" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Procesos Activos");

        jScrollPane1.setViewportView(jList1);

        btnAgregarProceso.setText("Agregar");

        btnReinicio.setText("Reiniciar");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Algoritmo de Ubicación");

        btnGroup.add(radio2);
        radio2.setText("Siguiente ajuste");

        btnGroup.add(radio3);
        radio3.setText("Mejor Ajuste");

        btnGroup.add(radio1);
        radio1.setSelected(true);
        radio1.setText("Primer Ajuste");

        checkBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        checkBox.setText("Compactación");

        jScrollPane2.setViewportView(jList2);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Procesos Inactivos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBox)
                            .addComponent(radio1)
                            .addComponent(radio3)
                            .addComponent(radio2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(comboProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAgregarProceso))
                            .addComponent(btnReinicio)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnReinicio)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarProceso))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(radio1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio3)
                .addGap(18, 18, 18)
                .addComponent(checkBox)
                .addGap(204, 204, 204))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProceso;
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnReinicio;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JComboBox<String> comboProceso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    // End of variables declaration//GEN-END:variables
}
