/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.udistrital.modelosmemoria.presentacionPrincipal;

import javax.swing.JMenuItem;

/**
 *
 * @author linkyava
 */
public class VistaPrincipal extends javax.swing.JFrame {
   
    private ModeloPrincipal miModelo;
    private ControladorPrincipal miControlador;
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal(ModeloPrincipal modelo) {
        miModelo = modelo;
        initComponents();
        capturarEventos();
    }
    
    public ControladorPrincipal getControl() {
        if(miControlador == null){
            miControlador = new ControladorPrincipal(this);
        }
        return miControlador;
    }
    
    public void capturarEventos(){
        jMenuEstaticaF.addActionListener(getControl());
        jMenuEstaticaV.addActionListener(getControl());
        jMenuDinamicaS.addActionListener(getControl());
        jMenuDinamicaC.addActionListener(getControl());
        jMenuSegmentacion.addActionListener(getControl());
        jMenuPaginacion.addActionListener(getControl());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuOpciones = new javax.swing.JMenuBar();
        JMenuPrincipal = new javax.swing.JMenu();
        jMenuEstaticaF = new javax.swing.JMenuItem();
        jMenuEstaticaV = new javax.swing.JMenuItem();
        jMenuDinamicaS = new javax.swing.JMenuItem();
        jMenuDinamicaC = new javax.swing.JMenuItem();
        jMenuSegmentacion = new javax.swing.JMenuItem();
        jMenuPaginacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Thonburi", 3, 24)); // NOI18N
        jLabel1.setText("Bienvenidos.");

        JMenuPrincipal.setText("Metodos");

        jMenuEstaticaF.setText("P. estáticas fijas");
        JMenuPrincipal.add(jMenuEstaticaF);

        jMenuEstaticaV.setText("P. estáticas variables");
        JMenuPrincipal.add(jMenuEstaticaV);

        jMenuDinamicaS.setText("P. dinamicas");
        JMenuPrincipal.add(jMenuDinamicaS);

        jMenuDinamicaC.setText("P. dinamicas con compactación");
        JMenuPrincipal.add(jMenuDinamicaC);

        jMenuSegmentacion.setText("P. Segmentación");
        JMenuPrincipal.add(jMenuSegmentacion);

        jMenuPaginacion.setText("P. Pagicación");
        JMenuPrincipal.add(jMenuPaginacion);

        jMenuOpciones.add(JMenuPrincipal);

        setJMenuBar(jMenuOpciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public ModeloPrincipal getMiModelo() {
        return miModelo;
    }

    public void setMiModelo(ModeloPrincipal miModelo) {
        this.miModelo = miModelo;
    }

    public ControladorPrincipal getMiControlador() {
        return miControlador;
    }

    public void setMiControlador(ControladorPrincipal miControlador) {
        this.miControlador = miControlador;
    }

    public JMenuItem getjMenuDinamicaC() {
        return jMenuDinamicaC;
    }

    public JMenuItem getjMenuDinamicaS() {
        return jMenuDinamicaS;
    }

    public JMenuItem getjMenuEstaticaF() {
        return jMenuEstaticaF;
    }

    public JMenuItem getjMenuEstaticaV() {
        return jMenuEstaticaV;
    }

    public JMenuItem getjMenuPaginacion() {
        return jMenuPaginacion;
    }

    public JMenuItem getjMenuSegmentacion() {
        return jMenuSegmentacion;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenuPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuDinamicaC;
    private javax.swing.JMenuItem jMenuDinamicaS;
    private javax.swing.JMenuItem jMenuEstaticaF;
    private javax.swing.JMenuItem jMenuEstaticaV;
    private javax.swing.JMenuBar jMenuOpciones;
    private javax.swing.JMenuItem jMenuPaginacion;
    private javax.swing.JMenuItem jMenuSegmentacion;
    // End of variables declaration//GEN-END:variables
}
