/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.udistrital.modelosmemoria.presentacion.segmentacion;

import java.awt.Graphics;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristian C4
 */
public class VistaSegmentacion extends javax.swing.JFrame {

    private ModeloSegmentacion miModelo;
    private ControladoSegmentacion miControlador;

    /**
     * Creates new form Vista
     */
    public VistaSegmentacion(ModeloSegmentacion modelo) {
        miModelo = modelo;
        initComponents();
        miModelo.iniciarMemoria(this, getContentPane());
        jComboTamParticion.setEnabled(miModelo.isEsEditablePartcion());
        btnParticionarMem.setEnabled(miModelo.isEsEditablePartcion());
        jLblModelo.setText(miModelo.isEsEditablePartcion() ? "Segmentación" : "Particiones estáticas variables");
        capturarEventos();
    }
    
    @Override
    public void paint (Graphics g)
    {
       super.paint(g);
    }

    public ControladoSegmentacion getControl() {
        if (miControlador == null) {
            miControlador = new ControladoSegmentacion(this);
        }
        return miControlador;
    }
    
    public void capturarEventos(){
        btnBorrar.addActionListener(this.getControl());
        btnCrearProceso.addActionListener(this.getControl());
        btnIniciar.addActionListener(this.getControl());
        btnParticionarMem.addActionListener(this.getControl());
    }

    public ModeloSegmentacion getMiModelo() {
        return miModelo;
    }

    public void setMiModelo(ModeloSegmentacion miModelo) {
        this.miModelo = miModelo;
    }

    public JButton getBtnBorrar() {
        return btnBorrar;
    }

    public JButton getBtnCrearProceso() {
        return btnCrearProceso;
    }

    public JButton getBtnIniciar() {
        return btnIniciar;
    }

    public JComboBox<String> getjComboTamParticion() {
        return jComboTamParticion;
    }
    
    public JLabel getjLblModelo() {
        return jLblModelo;
    }

    public void setjLblModelo(JLabel jLblModelo) {
        this.jLblModelo = jLblModelo;
    }

    public JTable getjTableProceso() {
        return jTableProceso;
    }

    public void setjTableProceso(JTable jTableProceso) {
        this.jTableProceso = jTableProceso;
    }

    public JTextField getTxtCodigo() {
        return txtCodigo;
    }

    public void setTxtCodigo(JTextField txtCodigo) {
        this.txtCodigo = txtCodigo;
    }

    public JTextField getTxtDatos() {
        return txtDatos;
    }

    public void setTxtDatos(JTextField txtDatos) {
        this.txtDatos = txtDatos;
    }

    public JTextField getTxtPila() {
        return txtPila;
    }

    public void setTxtPila(JTextField txtPila) {
        this.txtPila = txtPila;
    }

    public JButton getBtnParticionarMem() {
        return btnParticionarMem;
    }
   
    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDatos = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtPila = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblParticiones = new javax.swing.JLabel();
        jComboTamParticion = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProceso = new javax.swing.JTable();
        btnBorrar = new javax.swing.JButton();
        jLblModelo = new javax.swing.JLabel();
        btnCrearProceso = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnParticionarMem = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 102)));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setText("Proceso");

        jLabel7.setText("Datos :");

        jLabel8.setText("Codigo :");

        jLabel9.setText("Pila: ");

        txtPila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPilaActionPerformed(evt);
            }
        });

        jLabel1.setText("Kbs");

        jLabel2.setText("Kbs");

        jLabel3.setText("Kbs");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigo)
                                    .addComponent(txtDatos)
                                    .addComponent(txtPila, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel6)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPila, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 290, 200));

        btnIniciar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 270, 60));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 51)));

        lblParticiones.setText("Tamaño de partición en kbps:");

        jComboTamParticion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "256", "512", "1024", "2048" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblParticiones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jComboTamParticion, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblParticiones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboTamParticion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 270, 80));

        jTableProceso.setBackground(new java.awt.Color(204, 204, 204));
        jTableProceso.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 51)));
        jTableProceso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PID", "Tamaño total", "Detalle", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProceso.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTableProceso.setShowGrid(true);
        jTableProceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProcesoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableProceso);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 340, 370));

        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 250, -1));

        jLblModelo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        getContentPane().add(jLblModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 540, 40));

        btnCrearProceso.setText("Crear");
        btnCrearProceso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnCrearProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 136, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setText("Memoria");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, -1));

        btnParticionarMem.setText("Crear particiones");
        btnParticionarMem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(btnParticionarMem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 270, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPilaActionPerformed

    private void jTableProcesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProcesoMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modelTabla = (DefaultTableModel)getjTableProceso().getModel();
        if(!getjTableProceso().getSelectionModel().isSelectionEmpty()){
            String detalle = modelTabla.getValueAt(getjTableProceso().getSelectedRow(), 2).toString();
            JOptionPane.showMessageDialog(null, detalle, "Detalle partición", JOptionPane.CANCEL_OPTION);
        }
    }//GEN-LAST:event_jTableProcesoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCrearProceso;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnParticionarMem;
    private javax.swing.JComboBox<String> jComboTamParticion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblModelo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProceso;
    private javax.swing.JLabel lblParticiones;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDatos;
    private javax.swing.JTextField txtPila;
    // End of variables declaration//GEN-END:variables
}
